name: Lint via ESLint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  eslint:
    name: Run eslint scanning
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Install ESLint
        run: |
          npm install eslint@9.25.1
          npm install @microsoft/eslint-formatter-sarif@3.1.0
          npm install --save-dev svelte eslint eslint-plugin-svelte globals
      
      - name: Run ESLint
        env:
          SARIF_ESLINT_IGNORE_SUPRESSED: "true"
        run: npx eslint .
          --config eslint.config.js
          --format @microsoft/eslint-formatter-sarif
          --output-file eslint-results.sarif
        continue-on-error: true

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif-file: eslint-results.sarif
          wait-for-processing: true
